version: '3.9'

services:
  api:
    container_name: api
    build: .
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

  db:
    container_name: db_node_m6
    image: postgres:latest
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=m6_s3
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d m6_s3']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
